services:
  gateway-service:
    build:
      context: .
      dockerfile: ./apps/Gateway/Dockerfile
    command: node /app/dist/apps/Gateway/main.js
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - profile-service
      - content-service
      - metrics-service
      - comment-service
      - content-feed-service
      - rabbitmq
    environment:
      - AUTH_SERVICE_URL=auth-service:4010
      - GOOGLE_DRIVE_SERVICE_URL=google-drive-service:4020
      - PROFILE_SERVICE_URL=profile-service:4030
      - CONTENT_SERVICE_URL=content-service:4040
      - METRICS_SERVICE_URL=metrics-service:4050
      - COMMENT_SERVICE_URL=comment-service:4060
      - CONTENT_FEED_SERVICE_URL=content-feed-service:4070
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  auth-service:
    build:
      context: .
      dockerfile: ./apps/AuthService/Dockerfile
    command: node /app/dist/apps/AuthService/main.js
    env_file: .env
    depends_on:
      - rabbitmq
    environment:
      - AUTH_SERVICE_URL=auth-service:4010
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  google-drive-service:
    build:
      context: .
      dockerfile: ./apps/GoogleDriveService/Dockerfile
    command: node /app/dist/apps/GoogleDriveService/main.js
    env_file: .env
    depends_on:
      - rabbitmq
    environment:
      - GOOGLE_DRIVE_SERVICE_URL=google-drive-service:4020
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  profile-service:
    build:
      context: .
      dockerfile: ./apps/ProfileService/Dockerfile
    command: node /app/dist/apps/ProfileService/main.js
    env_file: .env
    depends_on:
      - google-drive-service
      - rabbitmq
    environment:
      - PROFILE_SERVICE_URL=profile-service:4030
      - GOOGLE_DRIVE_SERVICE_URL=google-drive-service:4020
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  content-service:
    build:
      context: .
      dockerfile: ./apps/ContentService/Dockerfile
    command: node /app/dist/apps/ContentService/main.js
    env_file: .env
    depends_on:
      - google-drive-service
      - metrics-service
      - rabbitmq
    environment:
      - CONTENT_SERVICE_URL=content-service:4040
      - GOOGLE_DRIVE_SERVICE_URL=google-drive-service:4020
      - METRICS_SERVICE_URL=metrics-service:4050
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  metrics-service:
    build:
      context: .
      dockerfile: ./apps/MetricsService/Dockerfile
    command: node /app/dist/apps/MetricsService/main.js
    env_file: .env
    depends_on:
      - rabbitmq
    environment:
      - METRICS_SERVICE_URL=metrics-service:4050
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  comment-service:
    build:
      context: .
      dockerfile: ./apps/CommentService/Dockerfile
    command: node /app/dist/apps/CommentService/main.js
    env_file: .env
    depends_on:
      - rabbitmq
    environment:
      - COMMENT_SERVICE_URL=comment-service:4060
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  content-feed-service:
    build:
      context: .
      dockerfile: ./apps/ContentFeedService/Dockerfile
    command: node /app/dist/apps/ContentFeedService/main.js
    env_file: .env
    depends_on:
      - auth-service
      - profile-service
      - metrics-service
    environment:
      - CONTENT_FEED_SERVICE_URL=content-feed-service:4070
      - AUTH_SERVICE_URL=auth-service:4010
      - PROFILE_SERVICE_URL=profile-service:4030
      - METRICS_SERVICE_URL=metrics-service:4050
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  rabbitmq_data:

