services:
  nx-app-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.base
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
